steps:
  - name: "gcr.io/cloud-builders/gcloud"
    dir: 'repo-scanner'
    id: "decrypt env"
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --project=github-quality-index
      - --keyring=deploy
      - --key=env
  - name: "gcr.io/cloud-builders/gcloud"
    dir: 'repo-scanner'
    id: "decrypt pem"
    args:
      - kms
      - decrypt
      - --ciphertext-file=github.pem.enc
      - --plaintext-file=github.pem
      - --location=global
      - --project=github-quality-index
      - --keyring=deploy
      - --key=github
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'repo-scanner'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/repo-scanner:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/repo-scanner:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/repo-scanner:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      [
        'beta', 
        'run', 
        'deploy', 
        'repo-scanner', 
        '--image', 
        'gcr.io/$PROJECT_ID/repo-scanner:$SHORT_SHA', 
        '--region', 
        'us-central1',
        '--allow-unauthenticated'
      ]
images:
  - 'gcr.io/$PROJECT_ID/repo-scanner:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/repo-scanner:latest'