export { getClient } from "./client";
export { isMasterProtected } from "./isMasterProtected"
export { isPrivate } from "./isPrivate";
export { reviews } from "./reviews";
export { snykInstalled } from "./snykInstalled";
export { usingCI } from "./usingCI";
export { numCommits } from "./numCommits";
export { daysSinceBump } from "./daysSinceBump";
export { hasLicense } from "./hasLicense";
